CREATE TABLE IF NOT EXISTS $tablename3
(id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    vendor_name VARCHAR (255) NOT NULL DEFAULT 'N/A',
    website VARCHAR (255) NOT NULL DEFAULT 'N/A',
    addr VARCHAR (255) NOT NULL DEFAULT 'N/A',
    email VARCHAR (255) NOT NULL DEFAULT 'N/A',
);